feat(ci): detect drift between local version and AUR

diff --git a/scripts/bin/ci_gen_pkgbuilds b/scripts/bin/ci_gen_pkgbuilds
--- a/scripts/bin/ci_gen_pkgbuilds
+++ b/scripts/bin/ci_gen_pkgbuilds
@@ -2,6 +2,11 @@
 
 set -euo pipefail
 
+BIN_DIR="$(cd -- "$(dirname $(readlink -f -- "${BASH_SOURCE[0]}"))" &>/dev/null && pwd)"
+LIB_DIR="$BIN_DIR/../lib"
+source "$LIB_DIR/aur.sh"
+source "$LIB_DIR/ci.sh"
+
 updated_packages=()
 
 for package in packages/*; do
@@ -11,7 +16,13 @@ for package in packages/*; do
     git add "$package/PKGBUILD"
     git diff
     if git diff-index --quiet HEAD "$package"; then
-        echo "No changes for $pp"
+        log::info "No changes for $pp, check if the AUR version differs from the local version"
+        aur_pkgbuild="/tmp/${pp}_aur/PKGBUILD"
+        aur:download_file "$pp" PKGBUILD > "$aur_pkgbuild"
+        if ! diff -q "$package/PKGBUILD" "$aur_pkgbuild"; then
+            log::info "AUR version differs from the local version, update is required"
+            updated_packages+=("$pp")
+        fi
     else
         git commit -m "chore: update $pp"
         git push
